local_directory = File.expand_path('../chef/', __FILE__)
core_directory = "#{local_directory}/../../core/chef/"

instance_eval(File.read("#{core_directory}/Berksfile.core.rb"))

gusztavvargadr_workstations_cookbook 'os', core_directory
gusztavvargadr_workstations_cookbook 'docker', core_directory
gusztavvargadr_workstations_cookbook 'git', core_directory
gusztavvargadr_workstations_cookbook 'vagrant', core_directory
gusztavvargadr_workstations_cookbook 'aws', core_directory

gusztavvargadr_cookbook 'windows'
