directory = File.expand_path('..', __FILE__)
require "#{directory}/../core/vagrant/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_core config

  gusztavvargadr_workstations_vm config, directory, 'docker' do |docker|
  end

  gusztavvargadr_workstations_vm config, directory, 'virtualbox' do |virtualbox|
  end

  gusztavvargadr_workstations_vm config, directory, 'aws' do |aws|
  end
end
