name 'gusztavvargadr_workstations_nuget'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures NuGet for workstations of gusztavvargadr'
long_description 'Installs/Configures NuGet for workstations of gusztavvargadr'
version '0.0.0'
