directory = File.expand_path('..', __FILE__)
require "#{directory}/../core/vagrant/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_core config

  gusztavvargadr_workstations_vm config, directory, 'w10e' do |w10e|
  end

  gusztavvargadr_workstations_vm config, directory, 'w16s' do |w16s|
  end
end
