local_directory = File.expand_path('../../../../chef/', __FILE__)
core_directory = local_directory

instance_eval(File.read("#{core_directory}/Berksfile.core.rb"))

gusztavvargadr_workstations_cookbook 'aws', local_directory
gusztavvargadr_workstations_cookbook 'os', local_directory

gusztavvargadr_cookbook 'windows'
