local_directory = File.expand_path('../chef/', __FILE__)
core_directory = "#{local_directory}/../../core/chef/"

instance_eval(File.read("#{core_directory}/Berksfile.common.rb"))

gusztavvargadr_workstations_cookbook 'dotnet', core_directory
gusztavvargadr_workstations_cookbook 'sql', core_directory

gusztavvargadr_workstations_cookbook 'common', core_directory
gusztavvargadr_workstations_cookbook 'os', core_directory
gusztavvargadr_workstations_cookbook 'docker', core_directory
gusztavvargadr_workstations_cookbook 'git', core_directory
gusztavvargadr_workstations_cookbook 'svn', core_directory
gusztavvargadr_workstations_cookbook 'nuget', core_directory

gusztavvargadr_cookbook 'windows'
