local_directory = File.expand_path('../', __FILE__)
core_directory = "#{local_directory}/../core/vagrant"

require "#{core_directory}/Vagrantfile.core"

Vagrant.configure('2') do |config|
  vagrant_config_vm_define(config, local_directory, 'vs10p', box: 'w16s-vs10p') do |vs10p|
  end

  vagrant_config_vm_define(config, local_directory, 'vs15c', box: 'w16s-vs15c') do |vs15c|
  end

  vagrant_config_vm_define(config, local_directory, 'vs15p', box: 'w16s-vs15p') do |vs15p|
  end

  vagrant_config_vm_define(config, local_directory, 'vs17c', box: 'w16s-vs17c') do |vs17c|
  end

  vagrant_config_vm_define(config, local_directory, 'vs17p', box: 'w16s-vs17p') do |vs17p|
  end
end
