directory = File.expand_path('..', __FILE__)
require "#{directory}/../core/vagrant/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_core config

  gusztavvargadr_workstations_vm config, directory, 'vs10p' do |vs10p|
  end

  gusztavvargadr_workstations_vm config, directory, 'vs15c' do |vs15c|
  end

  gusztavvargadr_workstations_vm config, directory, 'vs15p' do |vs15p|
  end

  gusztavvargadr_workstations_vm config, directory, 'vs17c' do |vs17c|
  end

  gusztavvargadr_workstations_vm config, directory, 'vs17p' do |vs17p|
  end
end
