src_directory = File.expand_path('../../..', __FILE__)
require "#{src_directory}/components/core/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, src_directory, ['stacks/sql/sql14'], 'sql14'
  gusztavvargadr_workstations_vm config, src_directory, ['stacks/sql/ssms16'], 'ssms16'
end
