directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, directory, 'sql14d'
  gusztavvargadr_workstations_vm config, directory, 'ssms16'
end
