directory = File.expand_path('..', __FILE__)
require "#{directory}/../core/vagrant/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_core config

  gusztavvargadr_workstations_vm config, directory, 'intellij' do |intellij|
  end

  gusztavvargadr_workstations_vm config, directory, 'eclipse' do |eclipse|
  end
end
