src_directory = File.expand_path('../../..', __FILE__)
instance_eval(File.read("#{src_directory}/components/core/Berksfile.core.rb"))

gusztavvargadr_workstations_cookbook src_directory, 'components', 'os'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'git'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'nuget'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'vagrant'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'docker'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'aws'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'ssms'
gusztavvargadr_workstations_cookbook src_directory, 'components', 'core'

gusztavvargadr_cookbook 'windows'
