directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, directory, 'work'
  gusztavvargadr_workstations_vm config, directory, 'playground'
  gusztavvargadr_workstations_vm config, directory, 'private'
end
