directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, directory, 'vs10p'
  gusztavvargadr_workstations_vm config, directory, 'vs15c'
  gusztavvargadr_workstations_vm config, directory, 'vs15p'
  gusztavvargadr_workstations_vm config, directory, 'vs17c'
  gusztavvargadr_workstations_vm config, directory, 'vs17p'
end
