directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, directory, 'aws'
  gusztavvargadr_workstations_vm config, directory, 'dockerc'
  gusztavvargadr_workstations_vm config, directory, 'dockere'
  gusztavvargadr_workstations_vm config, directory, 'virtualbox'
end
