include_recipe 'gusztavvargadr_workstations_os::tools'
include_recipe 'gusztavvargadr_workstations_docker::tools'
include_recipe 'gusztavvargadr_workstations_git::tools'
include_recipe 'gusztavvargadr_workstations_svn::tools'
include_recipe 'gusztavvargadr_workstations_nuget::tools'
