name 'gusztavvargadr_workstations_common'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures common workstations of gusztavvargadr'
long_description 'Installs/Configures common workstations of gusztavvargadr'
version '0.0.0'

depends 'gusztavvargadr_workstations_os'
depends 'gusztavvargadr_workstations_docker'
depends 'gusztavvargadr_workstations_git'
depends 'gusztavvargadr_workstations_svn'
depends 'gusztavvargadr_workstations_nuget'
