directory = File.expand_path('..', __FILE__)
require "#{directory}/../core/vagrant/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_core config

  gusztavvargadr_workstations_vm config, directory, 'sql14d' do |sql14d|
  end

  gusztavvargadr_workstations_vm config, directory, 'ssms16' do |ssms16|
  end
end
