local_directory = File.expand_path('../', __FILE__)
core_directory = "#{local_directory}/../core/vagrant"

require "#{core_directory}/Vagrantfile.core"

Vagrant.configure('2') do |config|
  vagrant_config_vm_define(config, local_directory, 'sql14d', box: 'w16s-sql14d') do |sql14d|
  end

  vagrant_config_vm_define(config, local_directory, 'ssms17', box: 'w16s') do |ssms17|
  end
end
