src_directory = File.expand_path('../../..', __FILE__)
require "#{src_directory}/components/core/Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, src_directory, ['stacks/os/w10'], 'w10'
  gusztavvargadr_workstations_vm config, src_directory, ['stacks/os/w16'], 'w16'
end
