directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  gusztavvargadr_workstations_vm config, directory, 'w10'
  gusztavvargadr_workstations_vm config, directory, 'w16'
end
